

export const products = [
  {
    id: 1,
    brand: "Havells",
    title: "Honor T17 0.1 GB RAM 8 GB ROM Tablet",
    price: 100.0,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-laptop.png",
    thumbs: [
      "../../public/images/cat-laptop.png",
      "../../public/images/cat-laptop.png",
      "../../public/images/cat-laptop.png",
    ],
  },
  {
    id: 2,
    brand: "Sony",
    title: "Alpha A6000 Mirrorless Digital Camera",
    price: 549.99,
    rating: 5,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-camera.png",
    thumbs: [
      "../../public/images/cat-camera.png",
      "../../public/images/cat-camera.png",
      "../../public/images/cat-camera.png",
    ],
  },
  {
    id: 3,
    brand: "Samsung",
    title: "55 Inch 4K Smart Television UHD",
    price: 799.0,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-tv.png",
    thumbs: [
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
    ],
  },
    {
    id: 1,
    brand: "Havells",
    title: "Honor T17 0.1 GB RAM 8 GB ROM Tablet",
    price: 100.0,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-laptop.png",
    thumbs: [
      "../../public/images/cat-laptop.png",
      "../../public/images/cat-laptop.png",
      "../../public/images/cat-laptop.png",
    ],
  },
  {
    id: 2,
    brand: "Sony",
    title: "Alpha A6000 Mirrorless Digital Camera",
    price: 549.99,
    rating: 5,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-camera.png",
    thumbs: [
      "../../public/images/cat-camera.png",
      "../../public/images/cat-camera.png",
      "../../public/images/cat-camera.png",
    ],
  },
  {
    id: 3,
    brand: "Samsung",
    title: "55 Inch 4K Smart Television UHD",
    price: 799.0,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-tv.png",
    thumbs: [
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
    ],
  },
    {
    id: 1,
    brand: "Havells",
    title: "Honor T17 0.1 GB RAM 8 GB ROM Tablet",
    price: 100.0,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-laptop.png",
    thumbs: [
      "../../public/images/cat-laptop.png",
      "../../public/images/cat-laptop.png",
      "../../public/images/cat-laptop.png",
    ],
  },
  {
    id: 2,
    brand: "Sony",
    title: "Alpha A6000 Mirrorless Digital Camera",
    price: 549.99,
    rating: 5,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-camera.png",
    thumbs: [
      "../../public/images/cat-camera.png",
      "../../public/images/cat-camera.png",
      "../../public/images/cat-camera.png",
    ],
  },
  {
    id: 3,
    brand: "Samsung",
    title: "55 Inch 4K Smart Television UHD",
    price: 799.0,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-tv.png",
    thumbs: [
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
    ],
  },
    {
    id: 1,
    brand: "Havells",
    title: "Honor T17 0.1 GB RAM 8 GB ROM Tablet",
    price: 100.0,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-laptop.png",
    thumbs: [
      "../../public/images/cat-laptop.png",
      "../../public/images/cat-laptop.png",
      "../../public/images/cat-laptop.png",
    ],
  },
  {
    id: 2,
    brand: "Sony",
    title: "Alpha A6000 Mirrorless Digital Camera",
    price: 549.99,
    rating: 5,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-camera.png",
    thumbs: [
      "../../public/images/cat-camera.png",
      "../../public/images/cat-camera.png",
      "../../public/images/cat-camera.png",
    ],
  },
  {
    id: 3,
    brand: "Samsung",
    title: "55 Inch 4K Smart Television UHD",
    price: 799.0,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-tv.png",
    thumbs: [
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
    ],
  },
    {
    id: 3,
    brand: "Samsung",
    title: "55 Inch 4K Smart Television UHD",
    price: 799.0,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-tv.png",
    thumbs: [
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
      "../../public/images/cat-tv.png",
    ],
  },
  {
    id: 4,
    brand: "Apple",
    title: "Apple Watch Series 9 GPS 45mm",
    price: 429.99,
    rating: 5,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-watch.png",
    thumbs: [
      "../../public/images/cat-watch.png",
      "../../public/images/cat-watch.png",
      "../../public/images/cat-watch.png",
    ],
  },
  {
    id: 5,
    brand: "Logitech",
    title: "Wireless Gaming Controller for Console",
    price: 89.99,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-gaming.png",
    thumbs: [
      "../../public/images/cat-gaming.png",
      "../../public/images/cat-gaming.png",
      "../../public/images/cat-gaming.png",
    ],
  },
  {
    id: 6,
    brand: "Xiaomi",
    title: "Redmi Note 13 Pro Smartphone 5G",
    price: 349.99,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-mobile.png",
    thumbs: [
      "../../public/images/cat-mobile.png",
      "../../public/images/cat-mobile.png",
      "../../public/images/cat-mobile.png",
    ],
  },
  {
    id: 7,
    brand: "JBL",
    title: "Over-Ear Wireless Bluetooth Headphones",
    price: 129.99,
    rating: 5,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-headphone.png",
    thumbs: [
      "../../public/images/cat-headphone.png",
      "../../public/images/cat-headphone.png",
      "../../public/images/cat-headphone.png",
    ],
  },
  {
    id: 8,
    brand: "Anker",
    title: "USB-C Multiport Charging Accessories Hub",
    price: 49.99,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-accessories.png",
    thumbs: [
      "../../public/images/cat-accessories.png",
      "../../public/images/cat-accessories.png",
      "../../public/images/cat-accessories.png",
    ],
  },
  {
    id: 9,
    brand: "Bose",
    title: "Portable Bluetooth Speaker with Deep Bass",
    price: 199.99,
    rating: 5,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-speaker.png",
    thumbs: [
      "../../public/images/cat-speaker.png",
      "../../public/images/cat-speaker.png",
      "../../public/images/cat-speaker.png",
    ],
  },
  {
    id: 10,
    brand: "Philips",
    title: "Smart Home Kitchen Appliances Blender",
    price: 159.99,
    rating: 4,
    discount: Math.floor(Math.random() * 50) + 5,
    image: "../../public/images/cat-home.png",
    thumbs: [
      "../../public/images/cat-home.png",
      "../../public/images/cat-home.png",
      "../../public/images/cat-home.png",
    ],
  },
];

